export enum USER_PERMISSION {
	READ = 'READ',
	WRITE = 'WRITE',
	DELETE = 'DELETE',
	UPDATE = 'UPDATE',
	CREATE = 'CREATE',
	VIEW = 'VIEW',
	UPLOAD = 'upload',
	DOWNLOAD = 'DOWNLOAD',
	EXPORT = 'EXPORT',
	ALL = 'ALL'
}
